# Generated by Django 3.1.7 on 2021-02-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_auto_20210222_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaul.jpg', upload_to='profile_pics'),
        ),
    ]
