# Generated by Django 3.1.7 on 2021-02-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username']},
        ),
    ]
