# Generated by Django 3.1.7 on 2021-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0006_auto_20210222_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_consumer',
            field=models.BooleanField(default=True),
        ),
    ]
